$(document).ready(function(){
	$("#lifirst").menu({"root":
				[
					{"name1":"123","url":"www.baidu.com"},
					{"name1":"国外公司","url":"www.baidu.com"},
					{"name1":"国内资讯","url":"www.baidu.com"},
					{"name1":"国外资讯","url":"www.baidu.com"},
					{"name1":"CATEGORY","url":"www.baidu.com"},
					{"name1":"-"},
					{"name1":"123","url":"www.baidu.com"},
					{"name1":"国外公司","url":"www.baidu.com"},
					{"name1":"国内资讯","url":"www.baidu.com"},
					{"name1":"国外资讯","url":"www.baidu.com"},
					{"name1":"CATEGORY","url":"www.baidu.com"}
				]
			});
	$("#lisecond").menu({"root":
				[
					{"name1":"123","url":"www.baidu.com"},
					{"name1":"国外公司","url":"www.baidu.com"},
					{"name1":"国内资讯","url":"www.baidu.com"},
					{"name1":"国外资讯","url":"www.baidu.com"},
					{"name1":"CATEGORY","url":"www.baidu.com"},
					{"name1":"-"},
					{"name1":"123","url":"www.baidu.com"},
					{"name1":"国外公司","url":"www.baidu.com"},
					{"name1":"国内资讯","url":"www.baidu.com"},
					{"name1":"国外资讯","url":"www.baidu.com"},
					{"name1":"CATEGORY","url":"www.baidu.com"}
				]
			});
	$("#lithird").menu({"root":
				[
					{"name1":"123","url":"www.baidu.com"},
					{"name1":"国外公司","url":"www.baidu.com"},
					{"name1":"国内资讯","url":"www.baidu.com"},
					{"name1":"国外资讯","url":"www.baidu.com"},
					{"name1":"CATEGORY","url":"www.baidu.com"},
					{"name1":"-"},
					{"name1":"123","url":"www.baidu.com"},
					{"name1":"国外公司","url":"www.baidu.com"},
					{"name1":"国内资讯","url":"www.baidu.com"},
					{"name1":"国外资讯","url":"www.baidu.com"},
					{"name1":"CATEGORY","url":"www.baidu.com"}
				]
			});
	$("#lifourd").menu({"root":
				[
					{"name1":"123","url":"www.baidu.com"},
					{"name1":"国外公司","url":"www.baidu.com"},
					{"name1":"国内资讯","url":"www.baidu.com"},
					{"name1":"国外资讯","url":"www.baidu.com"},
					{"name1":"CATEGORY","url":"www.baidu.com"},
					{"name1":"-"},
					{"name1":"123","url":"www.baidu.com"},
					{"name1":"国外公司","url":"www.baidu.com"},
					{"name1":"国内资讯","url":"www.baidu.com"},
					{"name1":"国外资讯","url":"www.baidu.com"},
					{"name1":"CATEGORY","url":"www.baidu.com"}
				]
			});
})